# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:24:41+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CertificateRequest(BaseModel):
    beneficiaryId: Optional[str] = None
    mobile: Optional[str] = None
